name: Hello GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
