name: Reusable Build

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Building application: ${{ inputs.application-name }}"
          mkdir build
          echo "Hello from ${{ inputs.application-name }}" > build/app.txt

      - name: Show build
        run: |
          cat build/app.txt
